version: "3.9"
services:
  mysql:
    restart: always
    container_name: "mysql"
    image: mysql:latest
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ecommercedb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password