# Generated by Django 5.0.6 on 2024-06-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField(max_length=30)),
                ("price", models.FloatField(default=0.0)),
                (
                    "type",
                    models.TextField(
                        choices=[
                            ("CPU_CHIP", "Cpu Chip"),
                            ("RAM", "Ram"),
                            ("GPU_CHIP", "Gpu Chip"),
                        ],
                        default="CPU_CHIP",
                    ),
                ),
                ("qty", models.IntegerField(default=0)),
                ("price_trending_date", models.DateField(null=True)),
            ],
        ),
    ]
