# Generated by Django 2.0.1 on 2019-04-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='econtact',
            field=models.CharField(default='0000', max_length=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='eemail',
            field=models.EmailField(default='sample@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='eid',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='ename',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
